run:
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - staticcheck
    - govet
    - ineffassign
    - unparam
    - misspell

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: .*_test\.go
      linters:
        - errcheck

