run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - misspell
    - gocyclo
    - unparam
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: adammathes.com/neko
