version: "2"
run:
  tests: true
  timeout: 5m

linters:
  default: none
  enable:
    - staticcheck
    - govet
    - ineffassign
    - unparam
    - misspell
  # If errcheck is enabled, exclude it for test files.
  # But since it's disabled globally, this rule is harmless but potentially unused.
  # The original config had it, so we keep it under the new location.
  exclusions:
    rules:
      - path: .*_test\.go
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
